services:
  neo4j:
    image: neo4j:5.26.2
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7474" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s


  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      neo4j:
        condition: service_healthy
    command: ["/bin/sh", "-c", "python setup.py && uvicorn app:app --host 0.0.0.0 --port 8080"]

volumes:
  neo4j_data:
  neo4j_logs:
